"""Preview changes to authored master geometry without rebuilding every UFO.

This does not optimize pixels or read reference outlines. Callers supply
geometry generated by a model; only differences between matching master
topologies are applied. A normal rebuild and full audit must validate a preview.
"""
import copy


class AuthoredPreview:
    """Keep the existing quadratic segment counts of an authored construction."""

    def __init__(self, font, key, construction):
        from fontTools.pens.recordingPen import RecordingPen
        record = RecordingPen()
        font['glyf'][key].draw(record, font['glyf'])
        self.counts = [len(points)-1 for op, points in record.value if op == 'qCurveTo']
        self.construction = construction
        self.scale = font['head'].unitsPerEm / 1000

    def glyph(self, profile):
        from fontTools.cu2qu.cu2qu import curves_to_quadratic
        from fontTools.pens.recordingPen import RecordingPen
        from fontTools.pens.ttGlyphPen import TTGlyphPen
        record = RecordingPen()
        self.construction(profile).replay(record, (self.scale, 0, 0, self.scale, 0, 0))
        pen, current, index = TTGlyphPen(None), None, 0
        calibration = [(0, 0), (0, 1), (1, 1), (1, 0)]
        errors = {2: .1, 3: .02, 4: .01, 5: .005, 6: .003}
        for op, points in record.value:
            if op == 'curveTo':
                count = self.counts[index]
                result = curves_to_quadratic([[current, *points], calibration],
                                             [1e9, errors[count]])[0]
                assert len(result) == count+2
                pen.qCurveTo(*result[1:])
                index += 1
            else:
                getattr(pen, op)(*points)
            if points:
                current = points[-1]
        assert index == len(self.counts), 'Cubic segmentation changed'
        return pen.glyph()

    def masters(self, profiles):
        return {(w, o): self.glyph(profiles[str(w)][o])
                for w in (100, 400, 900) for o in ('text', 'display')}

DISPLAY_SUPPORTS = ((0.01751708984375, 0.122802734375, 1.0),
                    (0.122802734375, 1.0, 1.0))
WEIGHT_SUPPORTS = {100: (-1.0, -1.0, 0.0), 900: (0.0, 1.0, 1.0)}


def replace_masters(font, key, before, after):
    """Apply six text/display master deltas, preserving metric-only tuples.

    before/after map (weight, 'text'|'display') to TTGlyphPen glyphs.
    All six original masters must match the compiled font at their peaks.
    Returns a copy so failed trials cannot change the input font.
    """
    base = font['glyf'][key]
    variations = font['gvar'].variations[key]
    n = len(base.coordinates)
    deltas = {}
    for (weight, optical), old in before.items():
        new = after[weight, optical]
        for glyph in (old, new):
            assert len(glyph.coordinates) == n, 'Master topology changed'
            assert list(glyph.endPtsOfContours) == list(base.endPtsOfContours)
            assert [f & 1 for f in glyph.flags] == [f & 1 for f in base.flags]
        # At these peaks only the ordinary geometry tuples contribute.
        peak = {'wght': {100: -1., 400: 0., 900: 1.}[weight],
                'opsz': 1. if optical == 'display' else 0.}
        from fontTools.varLib.models import supportScalar
        observed = [list(p) for p in base.coordinates]
        for v in variations:
            scalar = supportScalar(peak, v.axes)
            if scalar:
                for p, d in zip(observed, v.coordinates[:n]):
                    if d is not None:
                        p[0] += scalar*d[0]
                        p[1] += scalar*d[1]
        assert observed == [list(p) for p in old.coordinates], (key, weight, optical, 'Preview differs from compiled master')
        deltas[weight, optical] = [(b[0]-a[0], b[1]-a[1])
                                  for a, b in zip(old.coordinates, new.coordinates)]
    assert set(deltas) == {(w, o) for w in (100, 400, 900) for o in ('text', 'display')}

    def difference(a, b):
        return [(x[0]-y[0], x[1]-y[1]) for x, y in zip(a, b)]

    result = copy.deepcopy(font)
    default = deltas[400, 'text']
    for i, (dx, dy) in enumerate(default):
        x, y = result['glyf'][key].coordinates[i]
        result['glyf'][key].coordinates[i] = (x+dx, y+dy)
    optical_delta = difference(deltas[400, 'display'], default)
    touched = 0
    for v in result['gvar'].variations[key]:
        w, o = v.axes.get('wght'), v.axes.get('opsz')
        weight = next((weight for weight, support in WEIGHT_SUPPORTS.items() if support == w), None)
        if weight is not None and o is None:
            delta = difference(deltas[weight, 'text'], default)
        elif o in DISPLAY_SUPPORTS and w is None:
            delta = optical_delta
        elif o in DISPLAY_SUPPORTS and weight is not None:
            delta = difference(difference(deltas[weight, 'display'], deltas[weight, 'text']), optical_delta)
        else:
            continue
        assert len(v.coordinates) == n+4 and all(d is not None for d in v.coordinates[:n])
        for i, (dx, dy) in enumerate(delta):
            x, y = v.coordinates[i]
            v.coordinates[i] = (x+dx, y+dy)
        touched += 1
    assert touched == 8, 'Unexpected variation model'
    return result
