"""AST inventory of existing authored geometry; no edits to it."""
import ast,json,collections
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'build/font-recovery/project-analysis'
def main():
    assert json.loads((ROOT/'build/font-recovery/sfns-analysis/variation-metrics.json').read_text())['completed']
    OUT.mkdir(parents=True,exist_ok=True);files={};freq=collections.Counter()
    for p in sorted((ROOT/'scripts').glob('*.py')):
        source=p.read_text();tree=ast.parse(source);funs=[];assign=[];nums=[]
        for n in ast.walk(tree):
            if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef)):funs.append({'name':n.name,'line':n.lineno,'end':n.end_lineno,'arguments':ast.unparse(n.args)})
            if isinstance(n,(ast.Assign,ast.AnnAssign,ast.AugAssign)):assign.append({'line':n.lineno,'expression':ast.get_source_segment(source,n)})
            if isinstance(n,ast.Constant) and isinstance(n.value,(int,float)) and not isinstance(n.value,bool):nums.append({'line':n.lineno,'value':n.value});freq[str(n.value)]+=1
        files[str(p.relative_to(ROOT))]={'functions':funs,'assignments':assign,'numeric_literals':nums}
    measurements=json.loads((ROOT/'build/font-recovery/sfns-analysis/glyph-outlines.json').read_text())['glyphs']
    o=next(g for g in measurements if g['character']=='o')
    mapping=[['units_per_em','all','1000 internal / 2048 compiled','2048','Normalize lengths to em','high','design.py header; font-info.json'],['stem_vertical','shared','Design.s: 26→78→142 at w100→400→900',str(o['stem_vertical']/2.048)+' for o at defaults','Piecewise measured class-specific stem versus axes','medium','variation-metrics.json; center-scan proxy'],['stem_horizontal','bowls','s*.91 and other local ratios',str(o['stem_horizontal']/2.048),'Measured horizontal/vertical ratio per family','medium','glyph-outlines.json'],['cap_height','uppercase','1443/2.048','1443/2048 em','Shared cap height','high','OS/2.sCapHeight'],['x_height','lowercase','524-18*display','1040/2048 em at default','Measured optical interpolation','high','OS/2.sxHeight'],['overshoot','rounds','11 and local variants',str(o['overshoot_top']/2.048),'Shared round overshoot, separate ascender/descender rules','medium','glyph-outlines.json'],['advance_width','all','per-glyph width maps plus calibration modules','hmtx (full map in font-info.json)','Class rule with independent glyph residual','high','build.py Source.draw'],['sidebearing','all','space=42+10*(1-display)-5*(weight-400)/500; later calibration',str(o['left_sidebearing']/2.048),'Measured class spacing + optical exceptions','medium','hmtx plus outline bounds'],['curve_handle_ratio','rounds','ellipse .5522847498307936; bowl_curves local values','quadratic handles not directly comparable with cubic coefficients','Fit analytic original curve to scalar curvature landmarks, not Apple nodes','low','Different degree and segment topology'],['junction_compensation','branched','multiple independent local coefficients','not yet semantically segmented','Requires junction/terminal labels before fitting','insufficient','center scans mix stems with junctions']]
    data={'phase':5,'completed':True,'files':files,'repeated_numeric_literals':dict(freq.most_common()),'parameter_mapping':mapping,'interpretation':'Absolute coordinates, coefficient expressions and all function locations enumerated mechanically. Repetition is not by itself an error. Existing optical exceptions cannot be declared erroneous without class-specific evidence.'}
    (OUT/'project-geometry.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
    lines=['# Existing geometry and proposed shared parameters','','Primary dispatch: design.py → refined.py; primitives: geometry.py. Build pipeline applies numerous calibration modules after drawing.','', 'The recorded numbers are not a new generative model. Scalar SFNS observations do not uniquely recover semantic anchors or cubic control ratios.','','parameter | glyphs | current value | SFNS measured value | proposed shared rule | confidence | evidence','---|---|---|---|---|---|---']
    lines+=[' | '.join(row) for row in mapping]
    lines+=['','## Absolute versus normalized values','','Absolute coordinate tables and literals are listed by file and source line in project-geometry.json. Lengths can be normalized by UPM; dimensionless ratios must not be divided by UPM. Advance widths and sidebearings are modified after initial drawing, so initial width dictionaries are not final metrics.','','## Independent values and optical exceptions','','Differences in `.89`, `.82`, `s`, `sy`, `h`, `H`, `w`, `o`, and `heavy` expressions are recorded verbatim in the AST inventory. A repeated number can represent unrelated constructions. Only cap height and shared axis semantics are established invariants here; forcing other coefficients to equality would be unsupported. Cyrillic к/К/з/З/Я and digits 3/5 need independent semantic topology templates.','','## Evidence gap','','Center-scan thickness is a useful round-glyph measurement but is not a reliable stem/junction decomposition for branched or open contours. Counters represented by closed holes omit apertures. A scalar bounding box and area cannot determine terminal orientation, junction compensation, curve handles, or contour roles uniquely.']
    (OUT/'project-parameters.md').write_text('\n'.join(lines)+'\n')
    print('Inventoried',len(files),'Python modules')
if __name__=='__main__':main()
