"""Keep the configured character set and its OpenType/component dependencies."""
import json
import unicodedata
from pathlib import Path
from fontTools import subset


class OutlineDependencySubsetter(subset.Subsetter):
    """Keep an old component ID as outline data, without enabling its layout."""
    def _closure_glyphs(self, font):
        super()._closure_glyphs(font)
        reserved={'uni0308'}-set(font.getBestCmap().get(cp) for cp in self.unicodes_requested)
        # Equivalent to retaining it through glyf component closure. The
        # existing slot remains available, but is neither encoded nor added
        # to mark positioning. FontTools is pinned in requirements.lock.
        for stage in ('glyphs_requested','glyphs_cmaped','glyphs_mathed',
                      'glyphs_gsubed','glyphs_colred','glyphs_bslned'):
            value=getattr(self,stage)
            setattr(self,stage,value-reserved)


def apply(font, root):
    path = Path(root)/'sources/compact-charset.txt'
    characters = set(path.read_text().replace('\n','').replace('\r',''))
    required = {ord(c) for c in characters}
    missing = required - font.getBestCmap().keys()
    if missing:
        raise ValueError(f'Missing configured characters: {sorted(missing)}')
    options = subset.Options()
    options.layout_features = ['*']
    options.name_IDs = ['*']
    options.glyph_names = True
    options.notdef_outline = True
    worker = OutlineDependencySubsetter(options=options)
    worker.populate(unicodes=required, glyphs=['uni0308'] if 'uni0308' in font.getGlyphOrder() else [])
    worker.subset(font)
    assert set(font.getBestCmap()) == required
    rows = [{'codepoint':f'U+{cp:04X}','character':chr(cp),
             'name':unicodedata.name(chr(cp),'UNNAMED')} for cp in sorted(required)]
    text = json.dumps(rows,ensure_ascii=False,indent=2)
    (Path(root)/'sources/charset.json').write_text(text+'\n')
    (Path(root)/'sources/charset.js').write_text('// Generated by scripts/compact.py\nwindow.TABUNA_CHARSET = '+text+';\n')
